---
- name: Add FIM and Jump to OOBM ACL and Lines ACL
  vars:
    ansible_ios_commit_confirm_immediate: True
    ansible_ios_commit_confirm_timeout: 3
  connection: ansible.netcommon.network_cli
  hosts: all
  gather_facts: no

  tasks:
    - name: Add to OOBM ACL
      cisco.ios.ios_config:
        lines:
          - 6 permit ip 10.1.0.0 0.0.255.255 host 172.17.50.3
          - 7 permit ip host 172.17.50.3 10.1.0.0 0.0.255.255
          - 8 permit ip 10.1.0.0 0.0.255.255 host 172.17.50.8
          - 9 permit ip host 172.17.50.8 10.1.0.0 0.0.255.255
        parents: ip access-list extended 2088
  
    - name: Add to 122
      cisco.ios.ios_config:
        lines:
          - 6 permit ip 10.1.0.0 0.0.255.255 host 172.17.50.3
          - 7 permit ip host 172.17.50.3 10.1.0.0 0.0.255.255
          - 8 permit ip 10.1.0.0 0.0.255.255 host 172.17.50.8
          - 9 permit ip host 172.17.50.8 10.1.0.0 0.0.255.255
        parents: ip access-list extended 122

    

          #    - name: debug test
          #      debug:
          #        msg:
          #          - "ansible_conection: {{ ansible_connection }}"
          #          - "ansible_network_os: {{ ansible_network_os }}"
          #          - "ansible_user: {{ ansible_user }}"
          #          - "ansible_password: {{ ansible_password }}"
          #          - "ansible_become: {{ ansible_become }}"
