---
- name: Get Version of Node
  hosts: {{ host | default('all') }}
  gather_facts: no


  tasks:
    - name: Show uptime and version
      cisco.ios.ios_command:
        commands:
          - show version | i IOSXE.*Version.*RELEASE
          - show version | i BOOTLDR.*Version.*RELEASE
          - show version | i uptime
      register: show_output

    - name: Display raw output
      debug:
        var: show_output.stdout
